import { type NextPage } from "next";
import Head from "next/head";

import { api } from "~/utils/api";
import Layout from "~/lib/layout";
import { mainMenu } from "~/lib/menus";
import Link from "next/link";

const Home: NextPage = () => {
  const { data: courses } = api.getCourses.useQuery()
  const { data: subjects } = api.getMySubjects.useQuery()

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout
        title="Inicio"
        menu={mainMenu(courses)}
        nav={[]}
      >
        {subjects?.map(subject => (<Link key={subject.code} href={`/materia/${subject.code}`}>{}</Link>))}

        {subjects?.map(subject => (<Link key={subject.code}
          className="grid grid-cols-[75px,1fr] gap-4] p-2 px-4 hover:bg-gray-100 rounded-md border mt-2"
          href={`/materia/${subject.code}`}
        >
          <p>{subject.courseYear}° año</p>
          <p>{subject.name}</p>
        </Link>))}
      </Layout>
    </>
  );
};

export default Home